### ISSUE TITLE
mpYALMIP suppoert under WINDOWS

### ISSUE THREAD

**Issue by Mark-L-Stone** [giofantuzzi/mpYALMIP#1]
Do you have any plans to make mpYALMIP available under WINDOWS?  Would a WINDOWS version entail any inherent difficulties vs. LINUX?  Would you expect it to work under MATLAB R2014A (YALMIP does)?

Thanks.

**Comment by giofantuzzi** [comment]
Dear Mark,

the problem is that mpYALMIP relies on SDPA-GMP being installed, since it is only an interface to the solver. I do not know  how easy it is to compile and install SDPA-GMP and the required libraries on a Windows system: I have not tried, and unfortunately the installation instructions seem to assume that one is running a UNIX system. If you managed, could you please let me know?

As for mpYALMIP itself, it can be easily adapted to run on Windows. I will make the changes anyway, because it is better to have platform-independent code, and I will let you know when the code is available. 

Finally, I would expect mpYALMIP to work on any MATLAB version as long as YALMIP works, since all the code does is modify some YALMIP files and add some other ones.

Kind regards,
Giovanni

**Comment by giofantuzzi** [comment]
Dear Mark,

I have updated the codes, they should now run under Windows. However, I did not manage to install SDPA-GMP on my Windows machine, so I could not test if the codes actually work.

If you have managed to install SDPA-GMP on Windows, could you please let me know how, so I can do more tests?

Anyway, you should now be able to run

```
 >> install_sdpa_gmp('path-to-sdpa-gmp')
```

at the MATLAB prompt, replacing `'path-to-sdpa-gmp'` with the path to your SDPA-GMP executable file.
Let me know if you have any trouble, I'll do my best to help!

Kind regards,
Giovanni

**Comment by Mark-L-Stone** [comment]
Giovanni,

I have not attempted to install SDPA-GMP under WINDOWS.  Your probability of success is likely greater than mine.

**Comment by htadashi** [comment]
@Mark-L-Stone [mpYALMIP-neos](https://github.com/htadashi/mpYALMIP-neos) is a fork from mpYALMIP that sends the problem to the remote SDPA-GMP solver located on the [NEOS server](https://neos-server.org/neos/). It should run fine under Windows, as it does not need the SDPA-GMP executable to be installed in the local machine. 

@giofantuzzi Thanks again for creating mpYALMIP and for the useful advices regarding Github. I hope that with this fork more people can use mpYALMIP and SDPA-GMP :)

**Comment by giofantuzzi** [comment]
@htadashi no worries, thank you for developing it further!

**Comment by Mark-L-Stone** [comment]
Thanks for producing the sdpa-gmp-neos option.

However, I had fatal errors when I tried it.
```
>> A = [-1 2 0;-3 -4 1;0 0 -2];
>> P = sdpvar(3,3);
>> F = [P >= 0, A'*P+P*A <= 0, trace(P)==1];
>> obj = P(1,1);
>> sol = optimize(F,obj,sdpsettings('solver','sdpa-gmp-neos','verbose',1,'debug',1))
```
Creating NEOS server interface
Warning: Objects of redstone/xmlrpc/XmlRpcClient class exist - not clearing java 
> In javaclasspath>doclear at 377
  In javaclasspath>local_javapath at 194
  In javaclasspath at 119
  In javaaddpath at 71
  In NeosSDPAInterface>NeosSDPAInterface.NeosSDPAInterface at 9
  In callsdpagmp_neos at 111
  In solvesdp at 350
  In optimize at 31 
Job queue:
Running:
job#5272604  milp  CPLEX    AMPL  submitted 02/28 12:53 started 02/28 12:53 on neos-6.neos-
...
Queued:
No Jobs in Queue.
sol = 
    yalmiptime: 0.2481
    solvertime: 4.1169
          info: 'Successfully solved (SDPA-GMP-NEOS)'
       problem: 0
`>> P`
Index exceeds matrix dimensions.
Error in sdpvar/depends (line 14)
if ~any(variabletype(x.lmi_variables))
Error in sdpvar/display (line 83)
            vars = depends(X); 

YALMIP reported "Successfully solved".  But I know that this is reported by YALMIP for some solvers even when the problem is not successfully solved, due to some solver solution status reoorting/mapping difficulties.   The sdpvar P is obviously "screwed up" after optimize completes.  I don't know whether the warning "Warning: Objects of redstone/xmlrpc/XmlRpcClient class exist - not clearing java" is of any consequence, but I have received it on every invocation of optimize using sdpa-gmp--neos.

The output and error message on the sdpvar is basically the same even for this simple problem.
`>> x=sdpvar;sol = optimize(x>=0,x,sdpsettings('solver','sdpa-gmp-neos','verbose',1,'debug',1))`
Creating NEOS server interface
Warning: Objects of redstone/xmlrpc/XmlRpcClient class exist - not clearing java 
> In javaclasspath>doclear at 377
  In javaclasspath>local_javapath at 194
  In javaclasspath at 119
  In javaaddpath at 71
  In NeosSDPAInterface>NeosSDPAInterface.NeosSDPAInterface at 9
  In callsdpagmp_neos at 111
  In solvesdp at 350
  In optimize at 31 
Job queue:
Running:
job#5272604  milp  CPLEX    AMPL  submitted 02/28 12:53 started 02/28 12:53 on neos-6.neos-server.org
...

Queued:
No Jobs in Queue.
sol = 
    yalmiptime: 0.6347
    solvertime: 3.8353
          info: 'Successfully solved (SDPA-GMP-NEOS)'
       problem: 0
`>> x`
Index exceeds matrix dimensions.
Error in sdpvar/depends (line 14)
if ~any(variabletype(x.lmi_variables))
Error in sdpvar/display (line 10)
            vars = depends(X); 

I used MATLAB R2014A WIN64 under YALMIP-develop_2016_1215 with mpYALMIP-neos-master downloaded today.  I received no error messages or warnings when I executed 
```
>> javaclasspath('C:\mpYALMIP-neos-master/utils/xmlrpc-client-1.1.1.jar')
>> install_sdpa_gmp_neos 
```

**Comment by htadashi** [comment]
@Mark-L-Stone Thanks for reporting the error. Please try again using the command javaaddpath('C:\mpYALMIP-neos-master/utils/xmlrpc-client-1.1.1.jar') instead of using javaclasspath('C:\mpYALMIP-neos-master/utils/xmlrpc-client-1.1.1.jar').

**Comment by Mark-L-Stone** [comment]
I had already tried that as well and got the same result.
