### ISSUE TITLE
Interval Artithmetic Version of SDPA-GMP

### ISSUE THREAD

**Issue by Mark-L-Stone** [giofantuzzi/mpYALMIP#2]
What's the greatest number of digits you have tried under mpYALMIP or in any other version?  

Have you thought about modifying SDPA-GMP to use arbitrary precision outward rounded interval or radial arithmetic, so that rock-solid reliable calculations could be performed in a high enough precision to get rigorous, yet useful, results to difficult problems?

**Comment by giofantuzzi** [comment]
Dear Mark,

thanks for your interest in mpYALMIP. 

I have tried up to 250 digits of precision, but there should be no limit to how many digits you can use.

Regarding your suggestion of hacking SDPA-GMP to implement arbitrary precision interval arithmetic, I am not currently considering it.

 If a conic solver that implements interval arithmetic is what you are looking for, I can suggest VSDP (http://www.ti3.tuhh.de/jansson/vsdp/), although as far as I know it does not support multiple precision. 
In my experience, rescaling the problem to improve the numerical conditioning and then using VSDP is often sufficient. 

If you really need interval arithmetic and arbitrary precision, however, I would recommend that you contact the developers of SDPA-GMP or VSDP directly.

I hope this helps, please let me know if you have any more questions or suggestions.

Kind regards,
Giovanni

**Comment by Mark-L-Stone** [comment]
Giovanni,

Yes, I was thinking of something along the lines of VSDP, but with arbitrary precision (or at least higher than double precision) interval arithmetic.  Unfortunately, VSDP can easily be hamstrung by lack of precision. So although it may make verified conclusions, those verified conclusions can be too weak to be useful.

**Comment by giofantuzzi** [comment]
Dear Mark,

I see. It sounds like the problems you are dealing with are quite badly behaved. It may be more appropriate to speak with the developers of the solvers directly: they know their code, and they'll be able to add the functionalities you need much more quickly. 

Sorry I couldn't be of much help!

Best,
Giovanni
